[build]
  publish = "."
  command = "node generate-config.js"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "config.js"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
